---
title: "Visual-maps of michigan"
author: "Adham Rishmawi"
format: html
editor: visual
---

## Libraries

```{r warning=FALSE,message=FALSE}
library(ggplot2)
library(tidyverse)
library(ggmap)
library(maps)
library(dplyr)
library(revgeo)
library(sp)
library(sf)
library(tmap)
```

## Data sets + Map Data

```{r, warning=FALSE,message=FALSE}
Population_to_unknown_lines <- read_csv("~/Mcgregor Project/Data material/CSV-extracts from sql/Population_to_unknown_lines.csv")
map_data <- map_data("state", region= "michigan")
```

## Config Data sets to compatibility state

```{r, warning=FALSE,message=FALSE}
#google's API key
#ggmap::register_google(key = "AIzaSyB_bVP1ljY7VcsQDSEnJXW4AHWwBqMKmZU")


#altering data to add long and lat for cities
## cities_lat <- cbind(geocode(as.character(Population_to_unknown_lines$name)),Population_to_unknown_lines)
# Assuming your dataset is stored in a variable called "mydata"
## write.csv(cities_lat, file = "C:\\Users\\nader\\OneDrive\\Documents\\Mcgregor Project\\Data material\\CSV-extracts from sql\\cities_lat.csv", row.names = TRUE)

cities_lat <- read.csv("~/Mcgregor Project/Data material/CSV-extracts from sql/cities_lat.csv")

```

## Plotting Michigan-failed

```{r}
# MI <- map_data("state", region="michigan")
# ggplot(MI, aes(x=long, y=lat))+geom_polygon()
```

```{r}
# filtered_cities <- cities_lat %>%
#   filter(lon >= -91, lon <= -80, lat >= 41, lat <= 49)
# 
# ggplot(filtered_cities, aes(x = lon, y = lat)) +
#   geom_polygon() +
#   coord_map() +
#   geom_point(data = filtered_cities, aes(x = lon, y = lat), color = "orange")

```

## Map using package Tmap

```{r, warning=FALSE,message=FALSE}
# Convert cities_lat to an sf spatial object
cities_sf <- st_as_sf(na.omit(cities_lat), coords = c("lon", "lat")) |>
  subset(select = -X)


#making a porportion column

# Create the proportion column with default value of 0.01
cities_sf$proportion <-  cities_sf$Total_unknown / cities_sf$Total_service


cities_sf$proportion <- as.numeric(cities_sf$proportion)
# Assuming you have a data frame named 'cities_sf' with the 'proportion' column

cities_sf$percentage <- cities_sf$proportion * 100



# Create a tmap object
map <- tm_shape(cities_sf) +
  tm_symbols(col = "percentage", size = 0.03, palette = "RdYlBu") + 
  tm_layout(bg.color = "white")

# Set the map's extent to focus on Michigan
map <- map +
  tm_view(bbox = c(-90, 41, -80, 49))

# Display the map
tmap_mode("view")
tmap_style("albatross")
map

```

## Alter map to display proportions above 0.00

```{r,  warning=FALSE,message=FALSE}

filtered_cities_sf <- cities_sf %>%
  filter(proportion != 0)

# Create a tmap object
map_nonzero <- tm_shape(filtered_cities_sf) +
  tm_layout(bg.color = "white") +
  tm_bubbles("population",col = "percentage",size = 0.03 )

# Display the map
tmap_mode("view")
tmap_style("albatross")
map_nonzero +
tm_view(bbox = c(-90, 41, -80, 49))

```

## Make a map that displays unknown/total with heat map layout

```{r}
#FIGURE OUT HOW TO MAKE SPATIAL POINTS INTO POLYGONS

```
